# Generated by Django 2.0.1 on 2018-02-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_accountinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='account',
        ),
        migrations.AddField(
            model_name='statistics',
            name='account',
            field=models.ManyToManyField(to='tool.AccountInfo'),
        ),
    ]
