# Generated by Django 2.0.1 on 2018-02-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_auto_20180204_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='account',
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='link_to_files1',
            field=models.CharField(default='test', max_length=200),
        ),
    ]
