# Generated by Django 2.0.1 on 2018-02-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_auto_20180206_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinfo',
            name='resDict_path',
            field=models.CharField(default='test', max_length=200),
        ),
    ]
